### ISSUE TITLE
I can't find class com.opentable.service.AppInfo in anywhere?

### ISSUE THREAD

**Issue by eumji025** [opentable/otj-server#80]
When Used otj-server of version 2.12.7-SNAPSHOT in master branch, I can't find class of com.opentable.service.AppInfo in any dependency jar or in current classpath? 
it maybe in `otj-core` ? but I just find com.opentable.service.ServiceInfo,So  please tell me where can I find this class , thanks

**Comment by mikebell90** [comment]
Otj spring if I recall correctly. But you shouldn’t be using snapshots as a general rule

**Comment by eumji025** [comment]
Look forward the GA version, thank you
